### ISSUE TITLE
Fix [node|way|relation|changeset]/create

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-server#10]
Our implementation currently does not follow the API spec. First is the most problematic because JOSM (and potentially other clients) set `version=0` or a negative number when creating an element/changeset.

- [ ] Element or changeset id should be ignored on creation, currently if it is set it does an update operation: https://github.com/digidem/osm-p2p-server/blob/master/lib/routes.js#L74-L79
- [ ] Changeset creation with multiple changeset elements should not create multiple changesets, but tags in subsequent elements should override previous ones. [Spec says](http://wiki.openstreetmap.org/wiki/API_v0.6#Create:_PUT_.2Fapi.2F0.6.2Fchangeset.2Fcreate):

> If there are multiple changeset elements in the XML the tags from all of them are used, later ones overriding the earlier ones in case of duplicate keys.

From what I can see from the spec, this endpoint should always only return a single `id`, and only create one element/changeset.

**Comment by substack** [comment]
Fixed in 1.9.2 with some added test cases.
