### ISSUE TITLE
Placeholder ids in changeset uploads can be >= 0

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-server#12]
According to the OSM wiki, all ids on created elements in a changeset upload should be treated as placeholder ids (see [this note](http://wiki.openstreetmap.org/wiki/OsmChange#Placeholders)).

Currently I think we treat ids >=0 as actual ids? https://github.com/digidem/osm-p2p-server/blob/master/lib/xml_diff.js#L16

We should also probably do a couple of checks to make sure placeholder ids are unique and that they don't clash with other ids in the changeset.

**Comment by substack** [comment]
fixed in 1.9.3, but it doesn't yet ensure that placeholders don't clash with existing ids
