### ISSUE TITLE
Add endpoint Multi fetch: GET /api/0.6/[nodes|ways|relations]?#parameters

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-server#13]
http://wiki.openstreetmap.org/wiki/API_v0.6#Multi_fetch:_GET_.2Fapi.2F0.6.2F.5Bnodes.7Cways.7Crelations.5D.3F.23parameters

iD Editor makes a request on this endpoint when trying to save when not all parts of features being edited have been downloaded: https://github.com/openstreetmap/iD/blob/master/js/id/core/connection.js#L79-L92

**Comment by substack** [comment]
implemented in 1.10.0
