### ISSUE TITLE
malformed xml silently fails

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-server#16]
Running this command:

```
echo '<osm><changeset</changeset></osm>' | curl -sT- -H content-type:text/xml -X PUT localhost:5000/api/0.6/changeset/create
```

returns a changeset id, but the changeset does not actually exist, because trying to upload to the changeset id returns `not found`.

Clearly this is due to the syntax error in the xml, but it should not silently fail.

**Comment by substack** [comment]
fixed in 1.10.7
