### ISSUE TITLE
handle `if-unused` in changeset upload delete block

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-server#17]
The `"if-unused"` attribute in the delete block of a changeset upload should be checked for and handled. iD editor uses this key.

http://wiki.openstreetmap.org/wiki/API_v0.6#Diff_upload:_POST_.2Fapi.2F0.6.2Fchangeset.2F.23id.2Fupload

**Comment by gmaclennan** [comment]
it [looks like](https://github.com/openstreetmap/iD/blob/cdbca258aff0830aa12e11e4554c8978fd073dc3/js/lib/id/core.js#L1056) iD always sets this attribute, but we should definitely always check if any deleted nodes/ways are used in other entities before deleting.

**Comment by substack** [comment]
Implemented in 1.11.0 with tests.

**Comment by substack** [comment]
also need to implement precondition failures (412) for DELETE requests, not just changeset uploads
