### ISSUE TITLE
Coerce lat, lon to number and back to string

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-server#18]
OSM XML passes `lat` and `lon` as strings, but in osm-p2p-db these should be stored as numbers.

We should coerce `lat` and `lon` to numbers when putting/updating and convert back to string as part of xml conversion when reading

**Comment by substack** [comment]
addressed in 1.12.0: https://github.com/digidem/osm-p2p-server/commit/2804036fef67a043580cd3c0cbf0b6a441511b2a
