### ISSUE TITLE
XML responses should be ordered by element type

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-server#19]
According to the [OSM XML spec](http://wiki.openstreetmap.org/wiki/OSM_XML#Contents) the response should be ordered by element type:

1. nodes
2. ways
3. relations

The spec says:

> If you develop tools using this format, you can be certain that:
> * blocks come in this order

We currently do not enforce this order.

**Comment by substack** [comment]
fixed in 1.12.2
