### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-server#3]
Can we borrow from [macrocosm](https://github.com/developmentseed/macrocosm/tree/develop/test)'s tests? I don't quite understand macrocosm's decisions about the [API endpoints](http://devseed.com/macrocosm/#api-Changeset-UploadBulk). It would be nice to have something like `abstract-osm-server` with a common test suite that you could pass an array of endpoints you want to support.

**Comment by substack** [comment]
There are a fair number of tests now. macrocosm's tests have some assumptions about version properties that didn't work with the osm-p2p-db data model.
