### ISSUE TITLE
Changesets 

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-server#5]
We should support the creation of [changesets](http://wiki.openstreetmap.org/wiki/Changeset). This will require upstream changes in osm-p2p-db for storing changeset documents.

We need to implement endpoints for creating and closing changesets - see https://github.com/digidem/osm-p2p-server/issues/4

iD Editor creates a changeset, immediately uploads an [OsmChange](http://wiki.openstreetmap.org/wiki/OsmChange) document, and closes the changeset - see https://github.com/openstreetmap/iD/blob/master/js/id/core/connection.js#L268-L294

**Comment by substack** [comment]
The upstream changes in osm-p2p-db are ready for changesets.

**Comment by substack** [comment]
These are working in osm-p2p-server 1.3.0.
