### ISSUE TITLE
How to use with iD Editor

### ISSUE THREAD

**Issue by chfritz** [digidem/osm-p2p-server#53]
This is not an issue but a question that I couldn't find an answer to. The readme says that

> osm-p2p-server is tested and working with iD Editor

but I haven't been able to figure out how to set that up. I've tried setting the urlroot in https://github.com/openstreetmap/iD/blob/e495c991022a5b5b8f24ae8efab738397c30b954/modules/services/osm.js#L17 to 127.0.0.1:5000 where my osm-p2p-server is running (as somewhat hinted at in [iD Editor's FAQ](https://github.com/openstreetmap/iD/blob/develop/FAQ.md#can-i-use-id-with-my-own-osm-server)), but didn't work. The editor then complains about not being able to reach the OpenStreetMap API.

Are there any instructions for this anywhere or is my best bet to try and see how mapeo-desktop sets these two up together?

**Comment by okdistribute** [comment]
Hi @chfritz would you try [this fork of iD editor](https://github.com/digidem/iD-mapeo)? If I remember correctly, there are some hard-coded parts of iD that assume there is a connection to the API, and the fork removes those

**Comment by chfritz** [comment]
Hi @okdistribute , thanks for your help! I tried the fork. It didn't resolve the issue I had but helped me see it. It turned out to be a CORS issue. It's not completely working yet, but I got a step further by adding
```
    res.setHeader('Access-Control-Allow-Origin', '*')
```
to https://github.com/digidem/osm-p2p-server/blob/7d10243a88216a6f3e98465f3007f0881edc2309/index.js#L20-L22.

**Comment by chfritz** [comment]
Another issue I had was that iD Editor was requesting map updates using a route `../map.json?bbox` (instead of `../map?bbox`). This seems to have been a bug in the develop branch of iD which I was using but doesn't happen when using the latest release (2.2.1).

The CORS issue above is also avoided when merging iD Editor and osm-p2p-server into the same application server, which is straightforward given that iD Editor is a pure client-side application, i.e., only requires a web server serving static files.

**Comment by chfritz** [comment]
Correction: the latest version of iD is 2.20.1, of course, and using that one still shows the same issue -- the front end is requesting maps on `../map.json` instead of `../map`. This can be shimmed, but it does mean that out of the box osm-p2p-server doesn't right now work with iD.

Relevant issues:
- https://github.com/openstreetmap/iD/issues/3765
- https://github.com/digidem/osm-p2p-server/commit/f39e213ddbf4058b75d619e75aa30698bb4eedd4
